jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      # Install Terraform and other dependencies
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y unzip
            curl -O https://releases.hashicorp.com/terraform/1.3.6/terraform_1.3.6_linux_amd64.zip
            unzip terraform_1.3.6_linux_amd64.zip
            mv terraform /usr/local/bin/
            terraform version

      # Run Terraform
      - run:
          name: Run Terraform
          command: |
            terraform init
            terraform plan -input=false
            terraform apply -auto-approve
          env:
            DB_PASSWORD: ${DB_PASSWORD} # this needs to match up with a terraform input variable "db_password"!